#!/usr/bin/bash -eu

function main() {
	# local _self _orig_rustup;
	_self="$(readlink -f "$0")"
	_orig_rustup="$(command -v rustup.main)"

	function revert() {
		mv "$_self" "$_orig_rustup"
		printf '%s\n' "$(declare -f main)" 'main "$@"' >"$_self"
		chmod 0755 "$_self"
	}

	mv "$_orig_rustup" "$_self"
	trap revert ERR INT
	unset CARGO_HOME && { "$_self" "$@" || :; }
	revert
}
main "$@"
