# Sync all the images that are tagged using date time stamp
# format +%Y-%m-%d-%H-%M-%S e.g. 2022-02-22-10-10-54.
# Use simple regex for readability. Since we tag all images with year
# We use a regex rule: Any tag that starts with 'CURRENT_YEAR-CURRENT_MONTH'.
"europe-docker.pkg.dev/gitpod-artifacts/docker-dev":
  images-by-tag-regex:
    workspace-base: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-c: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-clojure: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-elixir: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-full: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-full-vnc: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-go: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-nix: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-node: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-node-lts: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-node-18: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-node-20: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-node-22: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-python: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-python-3.8: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-python-3.9: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-python-3.10: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-python-3.11: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-python-3.12: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-ruby-3: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-ruby-3.1: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-ruby-3.2: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-ruby-3.3: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-rust: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-dotnet: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-dotnet-6: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-dotnet-8: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-postgres: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-mysql: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-mongodb: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-java-11: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-java-17: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-java-21: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-yugabytedb: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-yugabytedb-preview: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-gitpod-dev: "CURRENT_YEAR-CURRENT_MONTH.*"
    workspace-bun: "CURRENT_YEAR-CURRENT_MONTH.*"
