# Sync all the image tags including latest
europe-docker.pkg.dev/gitpod-artifacts/docker-dev:
  images:
    workspace-base: []
    workspace-c: []
    workspace-clojure: []
    workspace-full: []
    workspace-full-vnc: []
    workspace-go: []
    workspace-node: []
    workspace-node-lts: []
    workspace-python: []
    workspace-ruby-2: []
    workspace-ruby-3: []
    workspace-rust: []
    workspace-dotnet-vnc: []
    workspace-postgresql: []
    workspace-mysql: []
    workspace-mongodb: []
    workspace-java-11: []
    workspace-java-17: []
