# Sync all the images that are tagged using date time stamp
# format +%Y-%m-%d-%H-%M-%S e.g. 2022-02-22-10-10-54.
# Use simple regex for readability. Since we tag all images with year
# We use a regex rule: Any tag that starts with '2023'.
"europe-docker.pkg.dev/gitpod-artifacts/docker-dev":
  images-by-tag-regex:
    workspace-base: "2023.*"
    workspace-c: "2023.*"
    workspace-clojure: "2023.*"
    workspace-elixir: "2023.*"
    workspace-full: "2023.*"
    workspace-full-vnc: "2023.*"
    workspace-go: "2023.*"
    workspace-nix: "2023.*"
    workspace-node: "2023.*"
    workspace-node-lts: "2023.*"
    workspace-python: "2023.*"
    workspace-python-3.11: "2023.*"
    workspace-python-3.12: "2023.*"
    workspace-ruby-3: "2023.*"
    workspace-ruby-3.0: "2023.*"
    workspace-ruby-3.1: "2023.*"
    workspace-ruby-3.2: "2023.*"
    workspace-rust: "2023.*"
    workspace-dotnet: "2023.*"
    workspace-postgres: "2023.*"
    workspace-mysql: "2023.*"
    workspace-mongodb: "2023.*"
    workspace-java-11: "2023.*"
    workspace-java-17: "2023.*"
    workspace-yugabytedb: "2023.*"
    workspace-yugabytedb-preview: "2023.*"
    workspace-gitpod-dev: "2023.*"
    workspace-bun: "2023.*"
