sync:
  images:
    workspace-base-images:
    - base
    - c
    - clojure
    - elixir
    - full
    - full-vnc
    - go
    - nix
    - node
    - node-lts
    - python
    - python-3.6
    - python-3.7
    - python-3.8
    - python-3.9
    - python-3.10
    - ruby-2
    - ruby-3
    - rust
    - dotnet
    - postgresql
    - mysql
    - mongodb
    - java-11
    - java-17
    - yugabytedb
