sync:
  images:
    workspace-base-images:
    - base
    - c
    - clojure
    - elixir
    - full
    - full-vnc
    - go
    - nix
    - node
    - node-lts
    - python
    - python-3.7
    - python-3.8
    - python-3.9
    - python-3.10
    - python-3.11
    - ruby-3
    - ruby-3.0
    - ruby-3.1
    - ruby-3.2
    - rust
    - dotnet
    - postgres
    - mysql
    - mongodb
    - java-11
    - java-17
    - yugabytedb
    - yugabytedb-preview
    - gitpod-dev
