sync:
  images:
    workspace-base-images:
    - base
    - c
    - clojure
    - full
    - full-vnc
    - go
    - node
    - node-lts
    - python
    - ruby-2
    - ruby-3
    - rust
    - dotnet-vnc
    - postgresql
    - mysql
    - mongodb
    - java-11
    - java-17

# these images are missing and need chunks and/or combinations

# workspace-dotnet-lts-vnc
# workspace-wasm
# workspace-flutter
# workspace-dotnet-lts
# workspace-dotnet
# workspace-gecko
