# https://github.com/containers/skopeo/blob/main/docs/skopeo-sync.1.md#yaml-file-content-used-source-for---src-yaml
localhost:5000:
  images:
    workspace-base-images:
    - base
    - c
    - clojure
    - full
    - full-vnc
    - go
    - node
    - node-lts
    - python
    - ruby-2
    - ruby
    - rust
    - dotnet-vnc
    - postgresql
    - mysql
    - mongodb
    - java-11

# these images are missing and need chunks and/or combinations

# workspace-dotnet-lts-vnc
# workspace-wasm
# mdbook ?
# workspace-flutter
# workspace-dotnet-lts
# workspace-dotnet
# workspace-gecko
