image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: ignore

tasks:
  - name: start up buildkitd
    command: |
      sudo /usr/bin/buildkitd --debug  --config ./buildkitd.toml --group gitpod
  - name: start a local docker registry
    command: |
      mkdir -p /workspace/registry
      docker run -p 5000:5000 --name registry --rm -v /workspace/registry:/var/lib/registry registry:2
    openMode: split-right
  - name: dazzle build and test
    before: |
      curl -sSL https://github.com/gitpod-io/dazzle/releases/download/v0.1.7/dazzle_0.1.7_Linux_x86_64.tar.gz | sudo tar -xvz -C /usr/local/bin
    command: |
      gp await-port 5000
      REPO=localhost:5000/dazzle
      echo "To build chunks and combinations 'time ./dazzle-up.sh'"
      echo "To list image chunks 'dazzle project image-name $REPO'"
      echo "To list hashes for image chunks 'dazzle project hash $REPO'"
      echo "To print the combined image maniest 'dazzle project manifest $REPO'"

    openMode: tab-after

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - timonwong.shellcheck

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
