image:
  file: .gitpod.Dockerfile

ports:
  - port: 5000
    onOpen: ignore

tasks:
  - name: install pre-commit git hooks
    init: pre-commit install
  - name: start up buildkitd
    command: |
      sudo /usr/bin/buildkitd --debug  --config ./buildkitd.toml --group gitpod
  - name: start a local docker registry
    command: |
      mkdir -p /workspace/registry
      docker run -p 5000:5000 --name registry --rm -v /workspace/registry:/var/lib/registry registry:2
    openMode: split-right
  - name: dazzle build and test
    command: |
      gp ports await 5000
      REPO=localhost:5000/dazzle
      echo "To build specific chunks and combine them 'time ./build-chunk.sh  -c chunk1 -c chunk2:variant1.2.3 -n combo'"
      echo "To build all the chunks and combinations 'time ./build-all.sh'"
      echo "To build a specific combination 'time ./build-combo.sh combo'"
      echo "To list image chunks 'dazzle project image-name $REPO'"
      echo "To list hashes for image chunks 'dazzle project hash $REPO'"
      echo "To print the combined image maniest 'dazzle project manifest $REPO'"

    openMode: tab-after

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - timonwong.shellcheck

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
