name: Delete PR registry images
on:
  schedule:
  # At 04:07 everyday. We choose such time as github recommends not choosing hourly timings
  # like 04:00 to avoid schedule job congestions
  - cron: 7 4 * * *

jobs:
  # delete the image tags and layers which are older than 4 days
  # this job is supposed to run everyday.
  delete:
    runs-on: ubuntu-latest
    environment: "pull-request"
    permissions:
      contents: "read"
      id-token: "write"
    env:
      WORKLOAD_IDENTITY_POOL_ID: projects/665270063338/locations/global/workloadIdentityPools/workspace-images-gh-actions-pr/providers/workspace-images-gha-provider-pr
      GAR_IMAGE_REGISTRY: europe-docker.pkg.dev
      IAM_SERVICE_ACCOUNT: workspace-images-gha-pr-sa@gitpod-artifacts.iam.gserviceaccount.com
    steps:
      - name: 📥 Checkout workspace-images
        uses: actions/checkout@v2
        with:
          repository: gitpod-io/workspace-images

      - name: ☁️ Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: 366.0.0

      - name: 🔐 Authenticate to Google Cloud
        id: "auth"
        uses: "google-github-actions/auth@v0.4.3"
        with:
          token_format: "access_token"
          workload_identity_provider: ${{env.WORKLOAD_IDENTITY_POOL_ID}}
          service_account: ${{env.IAM_SERVICE_ACCOUNT}}

      - name: 🖇️ Clean up images older than 4 days
        run: |
          TODAY=$(date '+%Y-%m-%d')
          DELETE_DATE=$(date --date="${TODAY} -4 day" +%Y-%m-%d)
          .github/gargc.sh ${{ env.GAR_IMAGE_REGISTRY }}/gitpod-artifacts/docker-dev-pr/workspace-base-images-pr ${DELETE_DATE}
